# Generated by Django 5.0.6 on 2024-05-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('patronymic', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('group', models.CharField(max_length=10)),
            ],
        ),
    ]
